### PR TITLE
Slight rework of tags code, replace struct with map, use replacer, merge in recent commits

### PR DESCRIPTION
**Pull request by jakebailey**
Here's what I worked on, as I mentioned in sorcix/irc#3.

It looks like @sorcix is around now, so maybe this won't matter. :smile:

### CODE REVIEW

**Comment by MorpheusXAUT** [comment]
I'll be glad to look into this in the evening today. As you've mentioned, @sorcix seems to be around as well though and has more commits to show, so hopefully our "problems" have been solved by that.

Appreciate the work and PR though!

**Comment by jakebailey** [comment]
No problem. Feel free to close this if you don't want it hanging around. (Not sure how heavily you use this repo anyway)

**Comment by sorcix** [comment]
I'll check this out tomorrow!

-- Vic

**Comment by MorpheusXAUT** [comment]
Since this is being merged into #3, I'll clone this PR here and will update/remove my fork once the changes land in master. Thanks for the work @jakebailey and @sorcix

**Pull request closed without merging**
